name: SPFx CI CD

on:
  push:
    branches:
      - main

env:
  packagePath: sharepoint/solution/testmap.sppkg

jobs:
  build:
    runs-on: windows-latest
    environment: trdeve5
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm ci
    
    - name: Build solution
      run: gulp build
              
    - name: Bundle and package
      run: |
        gulp bundle --ship
        gulp package-solution --ship
        
    - name: Upload Build Package
      uses: actions/upload-artifact@v2
      with:
        path: ${{ env.packagePath }}
        
        # Login to tenant using action-cli-login
    - name: Office 365 CLI Login
      uses: pnp/action-cli-login@v2.0.0
      with:
        ADMIN_USERNAME:  '${{ secrets.ADMINUSERNAME }}'
        ADMIN_PASSWORD:  '${{ secrets.ADMINPASSWORD }}'
    
    # Deploy package to tenant using action-cli-deploy
    - name: Office 365 CLI Deploy
      uses: pnp/action-cli-deploy@v2.0.0
      with:
        APP_FILE_PATH: sharepoint/solution/${{ env.packagePath }}
        # SKIP_FEATURE_DEPLOYMENT: true
        # OVERWRITE: true
    
    # Send an email using action-cli-runscript
    - name: Office 365 CLI Send email
      uses: pnp/action-cli-runscript@v2.0.0
      with:
         O365_CLI_SCRIPT: o365 spo mail send --webUrl ${{ secrets.SITECOLLECTION }} --to '${{ secrets.ADMINUSERNAME }}' --subject 'Deployment done' --body '<h2>Office 365 CLI</h2> <p>The deployment is complete.</p> <br/> Email sent via Office 365 CLI GitHub Action.'
      if: env.SEND_MAIL == 'true'
